export const data = {
  location: {
    name: "Ottawa",
    region: "Ontario",
    country: "Canada",
    lat: 45.42,
    lon: -75.69,
    tz_id: "America/Toronto",
    localtime_epoch: 1675699628,
    localtime: "2023-02-06 11:07",
  },
  current: {
    last_updated_epoch: 1675699200,
    last_updated: "2023-02-06 11:00",
    temp_c: -8,
    temp_f: 17.6,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 8.1,
    wind_kph: 13,
    wind_degree: 350,
    wind_dir: "N",
    pressure_mb: 1025,
    pressure_in: 30.26,
    precip_mm: 0,
    precip_in: 0,
    humidity: 67,
    cloud: 25,
    feelslike_c: -14.1,
    feelslike_f: 6.6,
    vis_km: 24,
    vis_miles: 14,
    uv: 2,
    gust_mph: 10.3,
    gust_kph: 16.6,
    air_quality: {
      co: 243.6999969482422,
      no2: 1.2000000476837158,
      o3: 67.19999694824219,
      so2: 0.800000011920929,
      pm2_5: 0.6000000238418579,
      pm10: 0.699999988079071,
      "us-epa-index": 1,
      "gb-defra-index": 1,
    },
  },
  forecast: {
    forecastday: [
      {
        date: "2023-02-06",
        date_epoch: 1675641600,
        day: {
          maxtemp_c: -2.7,
          maxtemp_f: 27.1,
          mintemp_c: -15.6,
          mintemp_f: 3.9,
          avgtemp_c: -5.7,
          avgtemp_f: 21.7,
          maxwind_mph: 11,
          maxwind_kph: 17.6,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 7,
          avgvis_miles: 4,
          avghumidity: 88,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 2,
        },
        astro: {
          sunrise: "07:18 AM",
          sunset: "05:17 PM",
          moonrise: "06:10 PM",
          moonset: "08:10 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: "100",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1675659600,
            time: "2023-02-06 00:00",
            temp_c: 0.2,
            temp_f: 32.4,
            is_day: 0,
            condition: {
              text: "Fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 203,
            wind_dir: "SSW",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 99,
            cloud: 100,
            feelslike_c: 0.2,
            feelslike_f: 32.4,
            windchill_c: 0.2,
            windchill_f: 32.4,
            heatindex_c: 0.2,
            heatindex_f: 32.4,
            dewpoint_c: 0,
            dewpoint_f: 32,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1,
          },
          {
            time_epoch: 1675663200,
            time: "2023-02-06 01:00",
            temp_c: 0.1,
            temp_f: 32.2,
            is_day: 0,
            condition: {
              text: "Fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            humidity: 99,
            cloud: 100,
            feelslike_c: 0.1,
            feelslike_f: 32.2,
            windchill_c: 0.1,
            windchill_f: 32.2,
            heatindex_c: 0.1,
            heatindex_f: 32.2,
            dewpoint_c: -0.1,
            dewpoint_f: 31.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 1,
          },
          {
            time_epoch: 1675666800,
            time: "2023-02-06 02:00",
            temp_c: 0,
            temp_f: 32,
            is_day: 0,
            condition: {
              text: "Freezing fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png",
              code: 1147,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 98,
            cloud: 95,
            feelslike_c: 0,
            feelslike_f: 32,
            windchill_c: 0,
            windchill_f: 32,
            heatindex_c: 0,
            heatindex_f: 32,
            dewpoint_c: -0.2,
            dewpoint_f: 31.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 1,
          },
          {
            time_epoch: 1675670400,
            time: "2023-02-06 03:00",
            temp_c: -0.3,
            temp_f: 31.5,
            is_day: 0,
            condition: {
              text: "Freezing fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png",
              code: 1147,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 226,
            wind_dir: "SW",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 82,
            feelslike_c: -2.6,
            feelslike_f: 27.3,
            windchill_c: -2.6,
            windchill_f: 27.3,
            heatindex_c: -0.3,
            heatindex_f: 31.5,
            dewpoint_c: -0.7,
            dewpoint_f: 30.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1675674000,
            time: "2023-02-06 04:00",
            temp_c: -1.2,
            temp_f: 29.8,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 275,
            wind_dir: "W",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 81,
            feelslike_c: -4.7,
            feelslike_f: 23.5,
            windchill_c: -4.7,
            windchill_f: 23.5,
            heatindex_c: -1.2,
            heatindex_f: 29.8,
            dewpoint_c: -2.1,
            dewpoint_f: 28.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1,
          },
          {
            time_epoch: 1675677600,
            time: "2023-02-06 05:00",
            temp_c: -7.3,
            temp_f: 18.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 318,
            wind_dir: "NW",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 30,
            feelslike_c: -11.8,
            feelslike_f: 10.8,
            windchill_c: -11.8,
            windchill_f: 10.8,
            heatindex_c: -7.3,
            heatindex_f: 18.9,
            dewpoint_c: -8.9,
            dewpoint_f: 16,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1,
          },
          {
            time_epoch: 1675681200,
            time: "2023-02-06 06:00",
            temp_c: -7,
            temp_f: 19.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 317,
            wind_dir: "NW",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 17,
            feelslike_c: -12.2,
            feelslike_f: 10,
            windchill_c: -12.2,
            windchill_f: 10,
            heatindex_c: -7,
            heatindex_f: 19.4,
            dewpoint_c: -9.1,
            dewpoint_f: 15.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15,
            gust_kph: 24.1,
            uv: 1,
          },
          {
            time_epoch: 1675684800,
            time: "2023-02-06 07:00",
            temp_c: -7,
            temp_f: 19.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 316,
            wind_dir: "NW",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 7,
            feelslike_c: -12.4,
            feelslike_f: 9.7,
            windchill_c: -12.4,
            windchill_f: 9.7,
            heatindex_c: -7,
            heatindex_f: 19.4,
            dewpoint_c: -9.5,
            dewpoint_f: 14.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.2,
            gust_kph: 27.7,
            uv: 1,
          },
          {
            time_epoch: 1675688400,
            time: "2023-02-06 08:00",
            temp_c: -7.9,
            temp_f: 17.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 0,
            feelslike_c: -13.9,
            feelslike_f: 7,
            windchill_c: -13.9,
            windchill_f: 7,
            heatindex_c: -7.9,
            heatindex_f: 17.8,
            dewpoint_c: -10.7,
            dewpoint_f: 12.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 18.1,
            gust_kph: 29.2,
            uv: 2,
          },
          {
            time_epoch: 1675692000,
            time: "2023-02-06 09:00",
            temp_c: -9.2,
            temp_f: 15.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 0,
            feelslike_c: -15.7,
            feelslike_f: 3.7,
            windchill_c: -15.7,
            windchill_f: 3.7,
            heatindex_c: -9.2,
            heatindex_f: 15.4,
            dewpoint_c: -12.1,
            dewpoint_f: 10.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.8,
            gust_kph: 27,
            uv: 2,
          },
          {
            time_epoch: 1675695600,
            time: "2023-02-06 10:00",
            temp_c: -9.1,
            temp_f: 15.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 318,
            wind_dir: "NW",
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            humidity: 79,
            cloud: 0,
            feelslike_c: -15.8,
            feelslike_f: 3.6,
            windchill_c: -15.8,
            windchill_f: 3.6,
            heatindex_c: -9.1,
            heatindex_f: 15.6,
            dewpoint_c: -12.1,
            dewpoint_f: 10.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 2,
          },
          {
            time_epoch: 1675699200,
            time: "2023-02-06 11:00",
            temp_c: -7.3,
            temp_f: 18.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 327,
            wind_dir: "NNW",
            pressure_mb: 1024,
            pressure_in: 30.24,
            precip_mm: 0,
            precip_in: 0,
            humidity: 78,
            cloud: 0,
            feelslike_c: -13.4,
            feelslike_f: 7.9,
            windchill_c: -13.4,
            windchill_f: 7.9,
            heatindex_c: -7.3,
            heatindex_f: 18.9,
            dewpoint_c: -10.5,
            dewpoint_f: 13.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 2,
          },
          {
            time_epoch: 1675702800,
            time: "2023-02-06 12:00",
            temp_c: -6.1,
            temp_f: 21,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 335,
            wind_dir: "NNW",
            pressure_mb: 1025,
            pressure_in: 30.25,
            precip_mm: 0,
            precip_in: 0,
            humidity: 78,
            cloud: 0,
            feelslike_c: -11.9,
            feelslike_f: 10.6,
            windchill_c: -11.9,
            windchill_f: 10.6,
            heatindex_c: -6.1,
            heatindex_f: 21,
            dewpoint_c: -9.3,
            dewpoint_f: 15.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 2,
          },
          {
            time_epoch: 1675706400,
            time: "2023-02-06 13:00",
            temp_c: -4.5,
            temp_f: 23.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 340,
            wind_dir: "NNW",
            pressure_mb: 1025,
            pressure_in: 30.25,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 0,
            feelslike_c: -9.5,
            feelslike_f: 14.9,
            windchill_c: -9.5,
            windchill_f: 14.9,
            heatindex_c: -4.5,
            heatindex_f: 23.9,
            dewpoint_c: -8,
            dewpoint_f: 17.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 2,
          },
          {
            time_epoch: 1675710000,
            time: "2023-02-06 14:00",
            temp_c: -3,
            temp_f: 26.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 341,
            wind_dir: "NNW",
            pressure_mb: 1025,
            pressure_in: 30.25,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 0,
            feelslike_c: -7.4,
            feelslike_f: 18.7,
            windchill_c: -7.4,
            windchill_f: 18.7,
            heatindex_c: -3,
            heatindex_f: 26.6,
            dewpoint_c: -6.7,
            dewpoint_f: 19.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 2,
          },
          {
            time_epoch: 1675713600,
            time: "2023-02-06 15:00",
            temp_c: -1.8,
            temp_f: 28.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 344,
            wind_dir: "NNW",
            pressure_mb: 1025,
            pressure_in: 30.27,
            precip_mm: 0,
            precip_in: 0,
            humidity: 75,
            cloud: 0,
            feelslike_c: -5.6,
            feelslike_f: 21.9,
            windchill_c: -5.6,
            windchill_f: 21.9,
            heatindex_c: -1.8,
            heatindex_f: 28.8,
            dewpoint_c: -5.6,
            dewpoint_f: 21.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 2,
          },
          {
            time_epoch: 1675717200,
            time: "2023-02-06 16:00",
            temp_c: -1.5,
            temp_f: 29.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 341,
            wind_dir: "NNW",
            pressure_mb: 1025,
            pressure_in: 30.27,
            precip_mm: 0,
            precip_in: 0,
            humidity: 75,
            cloud: 0,
            feelslike_c: -4.8,
            feelslike_f: 23.4,
            windchill_c: -4.8,
            windchill_f: 23.4,
            heatindex_c: -1.5,
            heatindex_f: 29.3,
            dewpoint_c: -5.4,
            dewpoint_f: 22.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 2,
          },
          {
            time_epoch: 1675720800,
            time: "2023-02-06 17:00",
            temp_c: -1.8,
            temp_f: 28.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 342,
            wind_dir: "NNW",
            pressure_mb: 1025,
            pressure_in: 30.27,
            precip_mm: 0,
            precip_in: 0,
            humidity: 76,
            cloud: 0,
            feelslike_c: -3.6,
            feelslike_f: 25.5,
            windchill_c: -3.6,
            windchill_f: 25.5,
            heatindex_c: -1.8,
            heatindex_f: 28.8,
            dewpoint_c: -5.4,
            dewpoint_f: 22.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 2,
          },
          {
            time_epoch: 1675724400,
            time: "2023-02-06 18:00",
            temp_c: -3.8,
            temp_f: 25.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 315,
            wind_dir: "NW",
            pressure_mb: 1026,
            pressure_in: 30.29,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 0,
            feelslike_c: -5.9,
            feelslike_f: 21.4,
            windchill_c: -5.9,
            windchill_f: 21.4,
            heatindex_c: -3.8,
            heatindex_f: 25.2,
            dewpoint_c: -6.5,
            dewpoint_f: 20.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
          {
            time_epoch: 1675728000,
            time: "2023-02-06 19:00",
            temp_c: -5.3,
            temp_f: 22.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 328,
            wind_dir: "NNW",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 0,
            feelslike_c: -8.3,
            feelslike_f: 17.1,
            windchill_c: -8.3,
            windchill_f: 17.1,
            heatindex_c: -5.3,
            heatindex_f: 22.5,
            dewpoint_c: -6.9,
            dewpoint_f: 19.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1,
          },
          {
            time_epoch: 1675731600,
            time: "2023-02-06 20:00",
            temp_c: -9.3,
            temp_f: 15.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 332,
            wind_dir: "NNW",
            pressure_mb: 1027,
            pressure_in: 30.33,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 0,
            feelslike_c: -13,
            feelslike_f: 8.6,
            windchill_c: -13,
            windchill_f: 8.6,
            heatindex_c: -9.3,
            heatindex_f: 15.3,
            dewpoint_c: -10.3,
            dewpoint_f: 13.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1675735200,
            time: "2023-02-06 21:00",
            temp_c: -10.3,
            temp_f: 13.5,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 324,
            wind_dir: "NW",
            pressure_mb: 1027,
            pressure_in: 30.33,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 20,
            feelslike_c: -13.9,
            feelslike_f: 7,
            windchill_c: -13.9,
            windchill_f: 7,
            heatindex_c: -10.3,
            heatindex_f: 13.5,
            dewpoint_c: -10.8,
            dewpoint_f: 12.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1675738800,
            time: "2023-02-06 22:00",
            temp_c: -11.3,
            temp_f: 11.7,
            is_day: 0,
            condition: {
              text: "Freezing fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png",
              code: 1147,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 333,
            wind_dir: "NNW",
            pressure_mb: 1028,
            pressure_in: 30.35,
            precip_mm: 0,
            precip_in: 0,
            humidity: 99,
            cloud: 50,
            feelslike_c: -13.7,
            feelslike_f: 7.3,
            windchill_c: -13.7,
            windchill_f: 7.3,
            heatindex_c: -11.3,
            heatindex_f: 11.7,
            dewpoint_c: -11.4,
            dewpoint_f: 11.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1675742400,
            time: "2023-02-06 23:00",
            temp_c: -12.4,
            temp_f: 9.7,
            is_day: 0,
            condition: {
              text: "Freezing fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png",
              code: 1147,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 344,
            wind_dir: "NNW",
            pressure_mb: 1028,
            pressure_in: 30.36,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 68,
            feelslike_c: -12.4,
            feelslike_f: 9.7,
            windchill_c: -12.4,
            windchill_f: 9.7,
            heatindex_c: -12.4,
            heatindex_f: 9.7,
            dewpoint_c: -12.8,
            dewpoint_f: 9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-02-07",
        date_epoch: 1675728000,
        day: {
          maxtemp_c: 2,
          maxtemp_f: 35.6,
          mintemp_c: -17.2,
          mintemp_f: 1,
          avgtemp_c: -7.6,
          avgtemp_f: 18.3,
          maxwind_mph: 18.8,
          maxwind_kph: 30.2,
          totalprecip_mm: 5.4,
          totalprecip_in: 0.21,
          totalsnow_cm: 1.36,
          avgvis_km: 6,
          avgvis_miles: 3,
          avghumidity: 95,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 76,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 6,
          condition: {
            text: "Moderate or heavy snow showers",
            icon: "//cdn.weatherapi.com/weather/64x64/day/371.png",
            code: 1258,
          },
          uv: 1,
        },
        astro: {
          sunrise: "07:16 AM",
          sunset: "05:18 PM",
          moonrise: "07:16 PM",
          moonset: "08:30 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: "98",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1675746000,
            time: "2023-02-07 00:00",
            temp_c: -14.6,
            temp_f: 5.7,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 357,
            wind_dir: "N",
            pressure_mb: 1028,
            pressure_in: 30.35,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 90,
            feelslike_c: -14.6,
            feelslike_f: 5.7,
            windchill_c: -14.6,
            windchill_f: 5.7,
            heatindex_c: -14.6,
            heatindex_f: 5.7,
            dewpoint_c: -15.1,
            dewpoint_f: 4.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1,
          },
          {
            time_epoch: 1675749600,
            time: "2023-02-07 01:00",
            temp_c: -15.6,
            temp_f: 3.9,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 69,
            wind_dir: "ENE",
            pressure_mb: 1028,
            pressure_in: 30.34,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 100,
            feelslike_c: -15.6,
            feelslike_f: 3.9,
            windchill_c: -15.6,
            windchill_f: 3.9,
            heatindex_c: -15.6,
            heatindex_f: 3.9,
            dewpoint_c: -16.2,
            dewpoint_f: 2.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
          {
            time_epoch: 1675753200,
            time: "2023-02-07 02:00",
            temp_c: -15.1,
            temp_f: 4.8,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1028,
            pressure_in: 30.35,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 99,
            feelslike_c: -15.1,
            feelslike_f: 4.8,
            windchill_c: -15.1,
            windchill_f: 4.8,
            heatindex_c: -15.1,
            heatindex_f: 4.8,
            dewpoint_c: -15.7,
            dewpoint_f: 3.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1,
          },
          {
            time_epoch: 1675756800,
            time: "2023-02-07 03:00",
            temp_c: -12.5,
            temp_f: 9.5,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 49,
            wind_dir: "NE",
            pressure_mb: 1028,
            pressure_in: 30.35,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 100,
            feelslike_c: -14.7,
            feelslike_f: 5.5,
            windchill_c: -14.7,
            windchill_f: 5.5,
            heatindex_c: -12.5,
            heatindex_f: 9.5,
            dewpoint_c: -13.1,
            dewpoint_f: 8.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1,
          },
          {
            time_epoch: 1675760400,
            time: "2023-02-07 04:00",
            temp_c: -9.8,
            temp_f: 14.4,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 86,
            wind_dir: "E",
            pressure_mb: 1027,
            pressure_in: 30.33,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 100,
            feelslike_c: -14.4,
            feelslike_f: 6.1,
            windchill_c: -14.4,
            windchill_f: 6.1,
            heatindex_c: -9.8,
            heatindex_f: 14.4,
            dewpoint_c: -10.3,
            dewpoint_f: 13.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1675764000,
            time: "2023-02-07 05:00",
            temp_c: -8.3,
            temp_f: 17.1,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 70,
            wind_dir: "ENE",
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 72,
            feelslike_c: -14.2,
            feelslike_f: 6.4,
            windchill_c: -14.2,
            windchill_f: 6.4,
            heatindex_c: -8.3,
            heatindex_f: 17.1,
            dewpoint_c: -9,
            dewpoint_f: 15.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1675767600,
            time: "2023-02-07 06:00",
            temp_c: -9.6,
            temp_f: 14.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 70,
            wind_dir: "ENE",
            pressure_mb: 1026,
            pressure_in: 30.31,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 39,
            feelslike_c: -15.9,
            feelslike_f: 3.4,
            windchill_c: -15.9,
            windchill_f: 3.4,
            heatindex_c: -9.6,
            heatindex_f: 14.7,
            dewpoint_c: -10.7,
            dewpoint_f: 12.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1,
          },
          {
            time_epoch: 1675771200,
            time: "2023-02-07 07:00",
            temp_c: -11.3,
            temp_f: 11.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 65,
            wind_dir: "ENE",
            pressure_mb: 1026,
            pressure_in: 30.3,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 32,
            feelslike_c: -17.7,
            feelslike_f: 0.1,
            windchill_c: -17.7,
            windchill_f: 0.1,
            heatindex_c: -11.3,
            heatindex_f: 11.7,
            dewpoint_c: -12.7,
            dewpoint_f: 9.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1,
          },
          {
            time_epoch: 1675774800,
            time: "2023-02-07 08:00",
            temp_c: -12.5,
            temp_f: 9.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1025,
            pressure_in: 30.27,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 34,
            feelslike_c: -19,
            feelslike_f: -2.2,
            windchill_c: -19,
            windchill_f: -2.2,
            heatindex_c: -12.5,
            heatindex_f: 9.5,
            dewpoint_c: -14,
            dewpoint_f: 6.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 2,
          },
          {
            time_epoch: 1675778400,
            time: "2023-02-07 09:00",
            temp_c: -12.7,
            temp_f: 9.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 90,
            wind_dir: "E",
            pressure_mb: 1024,
            pressure_in: 30.24,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 55,
            feelslike_c: -19.9,
            feelslike_f: -3.8,
            windchill_c: -19.9,
            windchill_f: -3.8,
            heatindex_c: -12.7,
            heatindex_f: 9.1,
            dewpoint_c: -14,
            dewpoint_f: 6.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 15,
            gust_kph: 24.1,
            uv: 2,
          },
          {
            time_epoch: 1675782000,
            time: "2023-02-07 10:00",
            temp_c: -11.7,
            temp_f: 10.9,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 88,
            feelslike_c: -19.3,
            feelslike_f: -2.7,
            windchill_c: -19.3,
            windchill_f: -2.7,
            heatindex_c: -11.7,
            heatindex_f: 10.9,
            dewpoint_c: -12.6,
            dewpoint_f: 9.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.5,
            gust_kph: 23.4,
            uv: 1,
          },
          {
            time_epoch: 1675785600,
            time: "2023-02-07 11:00",
            temp_c: -10.4,
            temp_f: 13.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 106,
            wind_dir: "ESE",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 89,
            feelslike_c: -17.8,
            feelslike_f: 0,
            windchill_c: -17.8,
            windchill_f: 0,
            heatindex_c: -10.4,
            heatindex_f: 13.3,
            dewpoint_c: -11.2,
            dewpoint_f: 11.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 1,
          },
          {
            time_epoch: 1675789200,
            time: "2023-02-07 12:00",
            temp_c: -9.2,
            temp_f: 15.4,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 110,
            wind_dir: "ESE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 77,
            feelslike_c: -16,
            feelslike_f: 3.2,
            windchill_c: -16,
            windchill_f: 3.2,
            heatindex_c: -9.2,
            heatindex_f: 15.4,
            dewpoint_c: -10.2,
            dewpoint_f: 13.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 1,
          },
          {
            time_epoch: 1675792800,
            time: "2023-02-07 13:00",
            temp_c: -7.4,
            temp_f: 18.7,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 119,
            wind_dir: "ESE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 100,
            feelslike_c: -14.7,
            feelslike_f: 5.5,
            windchill_c: -14.7,
            windchill_f: 5.5,
            heatindex_c: -7.4,
            heatindex_f: 18.7,
            dewpoint_c: -8.7,
            dewpoint_f: 16.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11,
            gust_kph: 17.6,
            uv: 1,
          },
          {
            time_epoch: 1675796400,
            time: "2023-02-07 14:00",
            temp_c: -6.3,
            temp_f: 20.7,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 130,
            wind_dir: "SE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 100,
            feelslike_c: -13.2,
            feelslike_f: 8.2,
            windchill_c: -13.2,
            windchill_f: 8.2,
            heatindex_c: -6.3,
            heatindex_f: 20.7,
            dewpoint_c: -7.8,
            dewpoint_f: 18,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1,
          },
          {
            time_epoch: 1675800000,
            time: "2023-02-07 15:00",
            temp_c: -1.5,
            temp_f: 29.3,
            is_day: 1,
            condition: {
              text: "Heavy snow",
              icon: "//cdn.weatherapi.com/weather/64x64/day/338.png",
              code: 1225,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 137,
            wind_dir: "SE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 95,
            cloud: 100,
            feelslike_c: -5.7,
            feelslike_f: 21.7,
            windchill_c: -5.7,
            windchill_f: 21.7,
            heatindex_c: -1.5,
            heatindex_f: 29.3,
            dewpoint_c: -2.2,
            dewpoint_f: 28,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1,
          },
          {
            time_epoch: 1675803600,
            time: "2023-02-07 16:00",
            temp_c: -0.6,
            temp_f: 30.9,
            is_day: 1,
            condition: {
              text: "Heavy snow",
              icon: "//cdn.weatherapi.com/weather/64x64/day/338.png",
              code: 1225,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 166,
            wind_dir: "SSE",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0.7,
            precip_in: 0.03,
            humidity: 93,
            cloud: 100,
            feelslike_c: -5.5,
            feelslike_f: 22.1,
            windchill_c: -5.5,
            windchill_f: 22.1,
            heatindex_c: -0.6,
            heatindex_f: 30.9,
            dewpoint_c: -1.6,
            dewpoint_f: 29.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 16.6,
            gust_kph: 26.6,
            uv: 1,
          },
          {
            time_epoch: 1675807200,
            time: "2023-02-07 17:00",
            temp_c: -0.5,
            temp_f: 31.1,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 15.9,
            wind_kph: 25.6,
            wind_degree: 186,
            wind_dir: "S",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 100,
            feelslike_c: -5.1,
            feelslike_f: 22.8,
            windchill_c: -5.1,
            windchill_f: 22.8,
            heatindex_c: -0.5,
            heatindex_f: 31.1,
            dewpoint_c: -2.3,
            dewpoint_f: 27.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 22.8,
            gust_kph: 36.7,
            uv: 1,
          },
          {
            time_epoch: 1675810800,
            time: "2023-02-07 18:00",
            temp_c: 2.3,
            temp_f: 36.1,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 17,
            wind_kph: 27.4,
            wind_degree: 196,
            wind_dir: "SSW",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 92,
            cloud: 100,
            feelslike_c: -3.2,
            feelslike_f: 26.2,
            windchill_c: -3.2,
            windchill_f: 26.2,
            heatindex_c: 2.3,
            heatindex_f: 36.1,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 23.7,
            gust_kph: 38.2,
            uv: 1,
          },
          {
            time_epoch: 1675814400,
            time: "2023-02-07 19:00",
            temp_c: 2.1,
            temp_f: 35.8,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 17,
            wind_kph: 27.4,
            wind_degree: 199,
            wind_dir: "SSW",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 94,
            cloud: 100,
            feelslike_c: -3.5,
            feelslike_f: 25.7,
            windchill_c: -3.5,
            windchill_f: 25.7,
            heatindex_c: 2.1,
            heatindex_f: 35.8,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 23.9,
            gust_kph: 38.5,
            uv: 1,
          },
          {
            time_epoch: 1675818000,
            time: "2023-02-07 20:00",
            temp_c: 0.6,
            temp_f: 33.1,
            is_day: 0,
            condition: {
              text: "Moderate snow",
              icon: "//cdn.weatherapi.com/weather/64x64/night/332.png",
              code: 1219,
            },
            wind_mph: 16.3,
            wind_kph: 26.3,
            wind_degree: 202,
            wind_dir: "SSW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 1.6,
            precip_in: 0.06,
            humidity: 97,
            cloud: 100,
            feelslike_c: -4.5,
            feelslike_f: 23.9,
            windchill_c: -4.5,
            windchill_f: 23.9,
            heatindex_c: 0.6,
            heatindex_f: 33.1,
            dewpoint_c: 0.2,
            dewpoint_f: 32.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 26.4,
            gust_kph: 42.5,
            uv: 1,
          },
          {
            time_epoch: 1675821600,
            time: "2023-02-07 21:00",
            temp_c: 1.9,
            temp_f: 35.4,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 203,
            wind_dir: "SSW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 96,
            cloud: 100,
            feelslike_c: -3.3,
            feelslike_f: 26.1,
            windchill_c: -3.3,
            windchill_f: 26.1,
            heatindex_c: 1.9,
            heatindex_f: 35.4,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 22.8,
            gust_kph: 36.7,
            uv: 1,
          },
          {
            time_epoch: 1675825200,
            time: "2023-02-07 22:00",
            temp_c: 2,
            temp_f: 35.6,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 205,
            wind_dir: "SSW",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 99,
            cloud: 100,
            feelslike_c: -3.1,
            feelslike_f: 26.4,
            windchill_c: -3.1,
            windchill_f: 26.4,
            heatindex_c: 2,
            heatindex_f: 35.6,
            dewpoint_c: 1.9,
            dewpoint_f: 35.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 21.5,
            gust_kph: 34.6,
            uv: 1,
          },
          {
            time_epoch: 1675828800,
            time: "2023-02-07 23:00",
            temp_c: 1.2,
            temp_f: 34.2,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 210,
            wind_dir: "SSW",
            pressure_mb: 1010,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            humidity: 100,
            cloud: 95,
            feelslike_c: -3.8,
            feelslike_f: 25.2,
            windchill_c: -3.8,
            windchill_f: 25.2,
            heatindex_c: 1.2,
            heatindex_f: 34.2,
            dewpoint_c: 1.1,
            dewpoint_f: 34,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 20.4,
            gust_kph: 32.8,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-02-08",
        date_epoch: 1675814400,
        day: {
          maxtemp_c: 0.6,
          maxtemp_f: 33.1,
          mintemp_c: -8.9,
          mintemp_f: 16,
          avgtemp_c: -2.3,
          avgtemp_f: 27.9,
          maxwind_mph: 16.8,
          maxwind_kph: 27,
          totalprecip_mm: 0.2,
          totalprecip_in: 0.01,
          totalsnow_cm: 0.17,
          avgvis_km: 7.6,
          avgvis_miles: 4,
          avghumidity: 89,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 78,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Light freezing rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/311.png",
            code: 1198,
          },
          uv: 1,
        },
        astro: {
          sunrise: "07:15 AM",
          sunset: "05:20 PM",
          moonrise: "08:21 PM",
          moonset: "08:48 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: "95",
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1675832400,
            time: "2023-02-08 00:00",
            temp_c: 1.8,
            temp_f: 35.2,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 217,
            wind_dir: "SW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            humidity: 100,
            cloud: 100,
            feelslike_c: -2.8,
            feelslike_f: 27,
            windchill_c: -2.8,
            windchill_f: 27,
            heatindex_c: 1.8,
            heatindex_f: 35.2,
            dewpoint_c: 1.8,
            dewpoint_f: 35.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.5,
            gust_kph: 31.3,
            uv: 1,
          },
          {
            time_epoch: 1675836000,
            time: "2023-02-08 01:00",
            temp_c: 1.9,
            temp_f: 35.4,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 236,
            wind_dir: "WSW",
            pressure_mb: 1010,
            pressure_in: 29.84,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 100,
            cloud: 100,
            feelslike_c: -2.6,
            feelslike_f: 27.3,
            windchill_c: -2.6,
            windchill_f: 27.3,
            heatindex_c: 1.9,
            heatindex_f: 35.4,
            dewpoint_c: 1.9,
            dewpoint_f: 35.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.5,
            gust_kph: 31.3,
            uv: 1,
          },
          {
            time_epoch: 1675839600,
            time: "2023-02-08 02:00",
            temp_c: 0.7,
            temp_f: 33.3,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 90,
            feelslike_c: -4.9,
            feelslike_f: 23.2,
            windchill_c: -4.9,
            windchill_f: 23.2,
            heatindex_c: 0.7,
            heatindex_f: 33.3,
            dewpoint_c: -1.2,
            dewpoint_f: 29.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 20.4,
            gust_kph: 32.8,
            uv: 1,
          },
          {
            time_epoch: 1675843200,
            time: "2023-02-08 03:00",
            temp_c: 1.8,
            temp_f: 35.2,
            is_day: 0,
            condition: {
              text: "Light snow",
              icon: "//cdn.weatherapi.com/weather/64x64/night/326.png",
              code: 1213,
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 264,
            wind_dir: "W",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            humidity: 91,
            cloud: 77,
            feelslike_c: -2.9,
            feelslike_f: 26.8,
            windchill_c: -2.9,
            windchill_f: 26.8,
            heatindex_c: 1.8,
            heatindex_f: 35.2,
            dewpoint_c: 0.4,
            dewpoint_f: 32.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.5,
            gust_kph: 31.3,
            uv: 1,
          },
          {
            time_epoch: 1675846800,
            time: "2023-02-08 04:00",
            temp_c: 1.4,
            temp_f: 34.5,
            is_day: 0,
            condition: {
              text: "Patchy light snow",
              icon: "//cdn.weatherapi.com/weather/64x64/night/323.png",
              code: 1210,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 267,
            wind_dir: "W",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 79,
            cloud: 34,
            feelslike_c: -3.7,
            feelslike_f: 25.3,
            windchill_c: -3.7,
            windchill_f: 25.3,
            heatindex_c: 1.4,
            heatindex_f: 34.5,
            dewpoint_c: -1.8,
            dewpoint_f: 28.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 21.5,
            gust_kph: 34.6,
            uv: 1,
          },
          {
            time_epoch: 1675850400,
            time: "2023-02-08 05:00",
            temp_c: -1.6,
            temp_f: 29.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 272,
            wind_dir: "W",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 27,
            feelslike_c: -7.6,
            feelslike_f: 18.3,
            windchill_c: -7.6,
            windchill_f: 18.3,
            heatindex_c: -1.6,
            heatindex_f: 29.1,
            dewpoint_c: -4.2,
            dewpoint_f: 24.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 20.4,
            gust_kph: 32.8,
            uv: 1,
          },
          {
            time_epoch: 1675854000,
            time: "2023-02-08 06:00",
            temp_c: -2.1,
            temp_f: 28.2,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 276,
            wind_dir: "W",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            humidity: 84,
            cloud: 84,
            feelslike_c: -7.4,
            feelslike_f: 18.7,
            windchill_c: -7.4,
            windchill_f: 18.7,
            heatindex_c: -2.1,
            heatindex_f: 28.2,
            dewpoint_c: -4.4,
            dewpoint_f: 24.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 1,
          },
          {
            time_epoch: 1675857600,
            time: "2023-02-08 07:00",
            temp_c: -2.1,
            temp_f: 28.2,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 77,
            feelslike_c: -7.6,
            feelslike_f: 18.3,
            windchill_c: -7.6,
            windchill_f: 18.3,
            heatindex_c: -2.1,
            heatindex_f: 28.2,
            dewpoint_c: -4.1,
            dewpoint_f: 24.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.3,
            gust_kph: 29.5,
            uv: 1,
          },
          {
            time_epoch: 1675861200,
            time: "2023-02-08 08:00",
            temp_c: -4.9,
            temp_f: 23.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 272,
            wind_dir: "W",
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 15,
            feelslike_c: -10.5,
            feelslike_f: 13.1,
            windchill_c: -10.5,
            windchill_f: 13.1,
            heatindex_c: -4.9,
            heatindex_f: 23.2,
            dewpoint_c: -7.8,
            dewpoint_f: 18,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.3,
            gust_kph: 29.5,
            uv: 2,
          },
          {
            time_epoch: 1675864800,
            time: "2023-02-08 09:00",
            temp_c: -2.7,
            temp_f: 27.1,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 284,
            wind_dir: "WNW",
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 65,
            feelslike_c: -8,
            feelslike_f: 17.6,
            windchill_c: -8,
            windchill_f: 17.6,
            heatindex_c: -2.7,
            heatindex_f: 27.1,
            dewpoint_c: -4.2,
            dewpoint_f: 24.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1,
          },
          {
            time_epoch: 1675868400,
            time: "2023-02-08 10:00",
            temp_c: -2.4,
            temp_f: 27.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 19,
            feelslike_c: -7.9,
            feelslike_f: 17.8,
            windchill_c: -7.9,
            windchill_f: 17.8,
            heatindex_c: -2.4,
            heatindex_f: 27.7,
            dewpoint_c: -4.4,
            dewpoint_f: 24.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 2,
          },
          {
            time_epoch: 1675872000,
            time: "2023-02-08 11:00",
            temp_c: -3,
            temp_f: 26.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 11,
            feelslike_c: -8.1,
            feelslike_f: 17.4,
            windchill_c: -8.1,
            windchill_f: 17.4,
            heatindex_c: -3,
            heatindex_f: 26.6,
            dewpoint_c: -5.9,
            dewpoint_f: 21.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 2,
          },
          {
            time_epoch: 1675875600,
            time: "2023-02-08 12:00",
            temp_c: -2,
            temp_f: 28.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 304,
            wind_dir: "NW",
            pressure_mb: 1023,
            pressure_in: 30.2,
            precip_mm: 0,
            precip_in: 0,
            humidity: 77,
            cloud: 6,
            feelslike_c: -7.3,
            feelslike_f: 18.9,
            windchill_c: -7.3,
            windchill_f: 18.9,
            heatindex_c: -2,
            heatindex_f: 28.4,
            dewpoint_c: -5.5,
            dewpoint_f: 22.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 2,
          },
          {
            time_epoch: 1675879200,
            time: "2023-02-08 13:00",
            temp_c: -1.7,
            temp_f: 28.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 301,
            wind_dir: "WNW",
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            humidity: 77,
            cloud: 16,
            feelslike_c: -6.8,
            feelslike_f: 19.8,
            windchill_c: -6.8,
            windchill_f: 19.8,
            heatindex_c: -1.7,
            heatindex_f: 28.9,
            dewpoint_c: -5.2,
            dewpoint_f: 22.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 2,
          },
          {
            time_epoch: 1675882800,
            time: "2023-02-08 14:00",
            temp_c: -1.1,
            temp_f: 30,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 294,
            wind_dir: "WNW",
            pressure_mb: 1023,
            pressure_in: 30.2,
            precip_mm: 0,
            precip_in: 0,
            humidity: 75,
            cloud: 8,
            feelslike_c: -5.9,
            feelslike_f: 21.4,
            windchill_c: -5.9,
            windchill_f: 21.4,
            heatindex_c: -1.1,
            heatindex_f: 30,
            dewpoint_c: -4.9,
            dewpoint_f: 23.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11,
            gust_kph: 17.6,
            uv: 2,
          },
          {
            time_epoch: 1675886400,
            time: "2023-02-08 15:00",
            temp_c: -0.8,
            temp_f: 30.6,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 282,
            wind_dir: "WNW",
            pressure_mb: 1023,
            pressure_in: 30.2,
            precip_mm: 0,
            precip_in: 0,
            humidity: 78,
            cloud: 69,
            feelslike_c: -5.1,
            feelslike_f: 22.8,
            windchill_c: -5.1,
            windchill_f: 22.8,
            heatindex_c: -0.8,
            heatindex_f: 30.6,
            dewpoint_c: -4.1,
            dewpoint_f: 24.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1,
          },
          {
            time_epoch: 1675890000,
            time: "2023-02-08 16:00",
            temp_c: -0.6,
            temp_f: 30.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 270,
            wind_dir: "W",
            pressure_mb: 1023,
            pressure_in: 30.22,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 58,
            feelslike_c: -5,
            feelslike_f: 23,
            windchill_c: -5,
            windchill_f: 23,
            heatindex_c: -0.6,
            heatindex_f: 30.9,
            dewpoint_c: -3.4,
            dewpoint_f: 25.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.2,
            gust_kph: 18,
            uv: 2,
          },
          {
            time_epoch: 1675893600,
            time: "2023-02-08 17:00",
            temp_c: 0.3,
            temp_f: 32.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 268,
            wind_dir: "W",
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 13,
            feelslike_c: -3.1,
            feelslike_f: 26.4,
            windchill_c: -3.1,
            windchill_f: 26.4,
            heatindex_c: 0.3,
            heatindex_f: 32.5,
            dewpoint_c: -2.5,
            dewpoint_f: 27.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 2,
          },
          {
            time_epoch: 1675897200,
            time: "2023-02-08 18:00",
            temp_c: -3.1,
            temp_f: 26.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1024,
            pressure_in: 30.25,
            precip_mm: 0,
            precip_in: 0,
            humidity: 91,
            cloud: 10,
            feelslike_c: -4.7,
            feelslike_f: 23.5,
            windchill_c: -4.7,
            windchill_f: 23.5,
            heatindex_c: -3.1,
            heatindex_f: 26.4,
            dewpoint_c: -4.4,
            dewpoint_f: 24.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1675900800,
            time: "2023-02-08 19:00",
            temp_c: -6.6,
            temp_f: 20.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 1025,
            pressure_in: 30.27,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 16,
            feelslike_c: -6.6,
            feelslike_f: 20.1,
            windchill_c: -6.6,
            windchill_f: 20.1,
            heatindex_c: -6.6,
            heatindex_f: 20.1,
            dewpoint_c: -7.6,
            dewpoint_f: 18.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 1,
          },
          {
            time_epoch: 1675904400,
            time: "2023-02-08 20:00",
            temp_c: -3.7,
            temp_f: 25.3,
            is_day: 0,
            condition: {
              text: "Freezing fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png",
              code: 1147,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 0,
            wind_dir: "N",
            pressure_mb: 1024,
            pressure_in: 30.23,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 15,
            feelslike_c: -6,
            feelslike_f: 21.2,
            windchill_c: -6,
            windchill_f: 21.2,
            heatindex_c: -3.7,
            heatindex_f: 25.3,
            dewpoint_c: -4.1,
            dewpoint_f: 24.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.9,
            gust_kph: 1.4,
            uv: 1,
          },
          {
            time_epoch: 1675908000,
            time: "2023-02-08 21:00",
            temp_c: -10.2,
            temp_f: 13.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 0.4,
            wind_kph: 0.7,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 1025,
            pressure_in: 30.28,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 19,
            feelslike_c: -10.2,
            feelslike_f: 13.6,
            windchill_c: -10.2,
            windchill_f: 13.6,
            heatindex_c: -10.2,
            heatindex_f: 13.6,
            dewpoint_c: -10.8,
            dewpoint_f: 12.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.9,
            gust_kph: 1.4,
            uv: 1,
          },
          {
            time_epoch: 1675911600,
            time: "2023-02-08 22:00",
            temp_c: -10.8,
            temp_f: 12.6,
            is_day: 0,
            condition: {
              text: "Mist",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1026,
            pressure_in: 30.29,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 20,
            feelslike_c: -12.5,
            feelslike_f: 9.5,
            windchill_c: -12.5,
            windchill_f: 9.5,
            heatindex_c: -10.8,
            heatindex_f: 12.6,
            dewpoint_c: -11.2,
            dewpoint_f: 11.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 1,
          },
          {
            time_epoch: 1675915200,
            time: "2023-02-08 23:00",
            temp_c: -5.6,
            temp_f: 21.9,
            is_day: 0,
            condition: {
              text: "Freezing fog",
              icon: "//cdn.weatherapi.com/weather/64x64/night/260.png",
              code: 1147,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 253,
            wind_dir: "WSW",
            pressure_mb: 1024,
            pressure_in: 30.24,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 45,
            feelslike_c: -8.8,
            feelslike_f: 16.2,
            windchill_c: -8.8,
            windchill_f: 16.2,
            heatindex_c: -5.6,
            heatindex_f: 21.9,
            dewpoint_c: -6,
            dewpoint_f: 21.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1,
          },
        ],
      },
    ],
  },
  alerts: {
    alert: [],
  },
};
